Vagrant.configure("2") do |config|
    config.winrm.retry_limit = 50
    config.winrm.retry_delay = 20
    config.winrm.timeout = 360
    config.vm.boot_timeout = 1200
    config.winrm.transport = :plaintext
    config.winrm.basic_auth_only = true
    config.winrm.username = "vagrant"
    config.winrm.password = "vagrant"
    config.vm.define  "controller" do |controller|
        
        controller.vm.box = "jacqinthebox/windowsserver2016"
        controller.vm.network "private_network", ip: "192.168.50.4", virtualbox__intnet: true
        controller.vm.provision "shell", path: "ctrl_prov_ADDomainServicesInstallation.ps1"  
        controller.vm.provision :reload
        controller.vm.provision "shell", path: "ctrl_prov_ad_config.ps1"      
        controller.vm.provision :reload
    end

    config.vm.define  "node1" do |node1|
        
        node1.vm.box = "jacqinthebox/windowsserver2016"
        node1.vm.provider "virtualbox" do |vb|
            vb.memory = "6144"
        end
        
        node1.vm.network "private_network", ip: "192.168.50.5", virtualbox__intnet: true

        node1.vm.provision "shell",inline: <<-SHELL
        slmgr /rearm
        Write-Host "Renaming host to node1"
        Rename-Computer node1 -Force
        Write-Host "Renaming finished"
        Exit 0
        SHELL

        node1.vm.provision :reload  
        node1.vm.provision "shell", path: "node1_joiningToDomain.ps1"
        node1.vm.provision :reload   
        node1.vm.provision "shell", path: "install-iis-features.ps1"
        node1.vm.provision :reload
        node1.vm.provision "shell", path: "install-sql-tools-and-choco.ps1"
        node1.vm.provision :reload
        node1.vm.provision "shell", path: "ssrs-auto-configuration.ps1"
        node1.vm.provision "shell", path: "extract-crm-setup.ps1"      
        node1.vm.provision "shell", path: "install-crm.ps1"
   end
  end